### PR TITLE
🚁🚇 Updated with Glitch

### PR DESCRIPTION
**Pull request by bentleycook**

### CODE REVIEW

**Comment by GenieCloud** [comment]
Hello @bentleycook I am attempting to build my first Trello PowerUp and in following the tutorial, I am not getting the 'manifest.json' file like demonstrated in the tutorial? Will this cause any issues with adding the PowerUp to a Trello Board?

**Comment by bentleycook** [comment]
@GenieCloud 🤦‍♀️ I've let it get out of date. I went ahead and opened an issue here: https://github.com/trello/glitch-trello-power-up/issues/7. Let me see if I can't get it caught back up.

**Comment by bentleycook** [comment]
@GenieCloud Which tutorial are you referring to? [This one](https://tech.trello.com/power-up-tutorial-part-one/) is up to date and doesn't mention the `manifest.json`.

**Comment by justincy** [comment]
Maybe she's referring to this page: https://developers.trello.com/docs/your-first-power-up

**Pull request merged**
